### ISSUE TITLE
clientBuilder.sslSocketFactory(SSLSocketFactory) not supported on JDK 9+

### ISSUE THREAD

**Issue by avdv** [featureflow/featureflow-java-sdk#4]
We are seeing this exception when trying to run our service on Java 11 (LTS):

```
Caused by: java.lang.UnsupportedOperationException: clientBuilder.sslSocketFactory(SSLSocketFactory) not supported on JDK 9+                      
        at okhttp3.internal.platform.Jdk9Platform.trustManager(Jdk9Platform.java:81)                                                               
        at okhttp3.internal.platform.Platform.buildCertificateChainCleaner(Platform.java:176)                                                      
        at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.java:655)                                                                    
        at io.featureflow.client.core.EventSource.<init>(EventSource.java:65)                                                                      
        at io.featureflow.client.core.FeatureControlStreamClient.start(FeatureControlStreamClient.java:62)                                         
        at io.featureflow.client.FeatureflowClient.<init>(FeatureflowClient.java:78)                                                               
        at io.featureflow.client.FeatureflowClient$Builder.build(FeatureflowClient.java:221)                                                       
...
```

**Comment by avdv** [comment]
This seems to be caused by a dependency of our service requiring a more recent okhttp3 library, namely `3.11.0`, while `featureflow-java-sdk` depends on `3.2.0` which gets evicted.

**Comment by avdv** [comment]
Just happened again, this time after upgrading `splunk-library-javalogging` to version 1.8.0, which depends on okhttp3 3.14.3.

Any chance this can be resolved or is the featureflow Java sdk dead?

**Comment by oliveroldfield** [comment]
Hi Claudio, thanks very much for your input. We  try to run the SDKs with as wide a compatibility matrix as possible (which should be 8 -> 11).. The guys are looking into this now. :)
